sudo: true
dist: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

before_install:
# TODO: can't get a server.key.enc to work - seems like a travis bug - https://github.com/travis-ci/travis-ci/issues/4746
# commited the server.key to git for now as a work around - NOT SECURE FOR A REAL DEV ORG/CODE
# https://trailhead.salesforce.com/modules/sfdx_travis_ci/units/sfdx_travis_ci_connected_app
#- openssl aes-256-cbc -K $encrypted_870902af7f35_key -iv $encrypted_870902af7f35_iv -in assets/server.key.enc -out assets/server.key -d
- wget -qO- $URL | tar xJf -
- ./sfdx/install
- export PATH=./sfdx/$(pwd):$PATH
#- sfdx update
#- sfdx --version
#- sfdx plugins --core

before_script:
# Authorize a Salesforce org using a private key file that has been uploaded to a personal connected app
# -i, --clientid CLIENTID         (required) OAuth client ID (sometimes called the consumer key)
# -u, --username USERNAME         (required) authentication username
# -f, --jwtkeyfile JWTKEYFILE     (required) path to a file containing the private key
# -a, --setalias SETALIAS         set an alias for the authenticated org
# -d, --setdefaultdevhubusername  set the authenticated org as the default dev hub org for scratch org creation
# -s, --setdefaultusername        set the authenticated org as the default username that all commands run against
- sfdx force:auth:jwt:grant -i $CONSUMERKEY -u $USERNAME -f assets/server.key -a DevHub -d

# create a scratch org
# -i, --clientid CLIENTID                          connected app consumer key
# -f, --definitionfile DEFINITIONFILE              path to a scratch org definition file
# -d, --durationdays DURATIONDAYS                  duration of the scratch org (in days) (default:7, min:1, max:30)
# -c, --noancestors                                do not include 2nd gen package ancestors in the scratch org
# -n, --nonamespace                                creates the scratch org with no namespace
# -a, --setalias SETALIAS                          set an alias for for the created scratch org
# -s, --setdefaultusername                         set the created org as the default username
# -v, --targetdevhubusername TARGETDEVHUBUSERNAME  username or alias for the dev hub org; overrides default dev hub org
# -w, --wait WAIT                                  the streaming client socket timeout (in minutes) (default:6, min:2)
# --json                                           format output as json
# --loglevel LOGLEVEL                              logging level for this command invocation (error*,trace,debug,info,warn,fatal)
- sfdx force:org:create -s -f config/project-scratch-def.json -a orgCI -w 10 --json

script:
- sfdx force:source:push -u orgCI
- sfdx force:apex:test:run -c -r human
- sleep 1m
- sfdx force:org:delete -u orgCI -p
