sudo: true
dist: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

before_install:
- openssl aes-256-cbc -K $encrypted_870902af7f35_key -iv $encrypted_870902af7f35_iv -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- wget -qO- $URL | tar xJf -
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx --version
- sfdx plugins --core

before_script:
- sfdx force --help
- sfdx force:auth:jwt:grant -i $CONSUMERKEY -u $USERNAME --jwtkeyfile assets/server.key --setdefaultdevhubusername

script:
- sfdx force:org:create -s -f config/project-scratch-def.json -a orgCI
 - sfdx force:source:push -u orgCI
 - sfdx force:apex:test:run -r human
 - sleep 1m
 - sfdx force:org:delete -u orgCI -p
